Controllers/ExchangeController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TraderData;
using TraderData.Models.FileImportModels;

namespace Trader.Controllers
{
    public class ExchangeController : BaseController
    {
        private readonly IReference _reference;

        public ExchangeController(IReference reference)
        {
            _reference = reference;    
        }

        // GET: Exchange
        public async Task<IActionResult> Index()
        {
            return View(await _reference.getExchanges());
        }

        // GET: Exchange/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var exchange = await _reference.GetExchangeById((int)id);
            if (exchange == null)
            {
                return NotFound();
            }

            return View(exchange);
        }

        // GET: Exchange/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Exchange/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ExchangeId,Name,URL")] Exchange exchange)
        {
            exchange.DateCreated = DateTime.Now;
            if (ModelState.IsValid)
            {
                await _reference.AddExchange(exchange);
                return RedirectToAction("Index");
            }
            return View(exchange);
        }

        // GET: Exchange/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var exchange = await _reference.GetExchangeById((int)id);
            if (exchange == null)
            {
                return NotFound();
            }
            return View(exchange);
        }

        // POST: Exchange/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ExchangeId,Name,URL")] Exchange exchange)
        {
            if (id != exchange.ExchangeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var res = await _reference.EditExchange(exchange);
                if (res)
                    return RedirectToAction("Index");
                else
                    return NotFound();
            }
            return View(exchange);
        }

        // GET: Exchange/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var exchange = await _reference.GetExchangeById((int)id);
            if (exchange == null)
            {
                return NotFound();
            }

            return View(exchange);
        }

        // POST: Exchange/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _reference.DeleteExchange(id);
            return RedirectToAction("Index");
        }

       
    }
}

Controllers/NewsItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TraderData;
using TraderData.Models.NewsModels;

namespace Trader.Controllers
{
    [Authorize]
    public class NewsItemsController : BaseController
    {
        private readonly ApplicationDbContext _context;

        public NewsItemsController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: NewsItems
        public async Task<IActionResult> Index()
        {
            return View(await _context.NewsItem.ToListAsync());
        }

        // GET: NewsItems/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var newsItem = await _context.NewsItem
                .SingleOrDefaultAsync(m => m.NewsItemID == id);
            if (newsItem == null)
            {
                return NotFound();
            }

            return View(newsItem);
        }

        // GET: NewsItems/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: NewsItems/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("NewsItemID,Title,Description,Ts")] NewsItem newsItem)
        {
            if (ModelState.IsValid)
            {
                _context.Add(newsItem);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(newsItem);
        }

        // GET: NewsItems/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var newsItem = await _context.NewsItem.SingleOrDefaultAsync(m => m.NewsItemID == id);
            if (newsItem == null)
            {
                return NotFound();
            }
            return View(newsItem);
        }

        // POST: NewsItems/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("NewsItemID,Title,Description,Ts")] NewsItem newsItem)
        {
            if (id != newsItem.NewsItemID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(newsItem);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NewsItemExists(newsItem.NewsItemID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(newsItem);
        }

        // GET: NewsItems/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var newsItem = await _context.NewsItem
                .SingleOrDefaultAsync(m => m.NewsItemID == id);
            if (newsItem == null)
            {
                return NotFound();
            }

            return View(newsItem);
        }

        // POST: NewsItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var newsItem = await _context.NewsItem.SingleOrDefaultAsync(m => m.NewsItemID == id);
            _context.NewsItem.Remove(newsItem);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool NewsItemExists(int id)
        {
            return _context.NewsItem.Any(e => e.NewsItemID == id);
        }
    }
}

Controllers/SettingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TraderData;
using TraderData.Models.AdminModels;

namespace Trader.Controllers
{
    public class SettingsController : BaseController
    {
        private readonly ApplicationDbContext _context;

        public SettingsController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: Settings
        public async Task<IActionResult> Index()
        {
            return View(await _context.Settings.ToListAsync());
        }

        // GET: Settings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var settings = await _context.Settings
                .SingleOrDefaultAsync(m => m.SettingsID == id);
            if (settings == null)
            {
                return NotFound();
            }

            return View(settings);
        }

        // GET: Settings/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Settings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SettingsID,RefreshTime")] Settings settings)
        {
            if (ModelState.IsValid)
            {
                _context.Add(settings);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(settings);
        }

        // GET: Settings/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var settings = await _context.Settings.SingleOrDefaultAsync(m => m.SettingsID == id);
            if (settings == null)
            {
                return NotFound();
            }
            return View(settings);
        }

        // POST: Settings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SettingsID,RefreshTime")] Settings settings)
        {
            if (id != settings.SettingsID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(settings);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SettingsExists(settings.SettingsID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(settings);
        }

        // GET: Settings/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var settings = await _context.Settings
                .SingleOrDefaultAsync(m => m.SettingsID == id);
            if (settings == null)
            {
                return NotFound();
            }

            return View(settings);
        }

        // POST: Settings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var settings = await _context.Settings.SingleOrDefaultAsync(m => m.SettingsID == id);
            _context.Settings.Remove(settings);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool SettingsExists(int id)
        {
            return _context.Settings.Any(e => e.SettingsID == id);
        }
    }
}

Controllers/TaxController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TraderData;
using TraderData.Models.TaxModels;
using TraderData.Models;
using TraderData.Models.TradeImportModels;

namespace Trader.Controllers
{
    [Authorize]
    public class TaxController : BaseController
    {
        private readonly ITrades _trades;
        private readonly IReference _reference;
        private readonly UserManager<ApplicationUser> _userManager;


        public TaxController(ITrades trades, UserManager<ApplicationUser> userManager, IReference reference)
        {
            _reference = reference;
            _trades = trades;
            _userManager = userManager;
        }
        public async Task<IActionResult> Index()
        {
			var user = await GetCurrentUserAsync();

			var userId = user?.Id;

			if (userId != null)
			{
                var tradesAsync = await _trades.getAllByUser(userId);
				return View(await CalculateTaxEvents(tradesAsync));
				
			}
			return NotFound();

        }

        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        public async Task<IEnumerable<TaxEventModel>> CalculateTaxEvents(IEnumerable<TradeImport> trades)
        {
            var sorted = trades.OrderBy(c => c.TransactionDate);

            var instruments = await _reference.getInstruments();
            List<TradeImport> holder = new List<TradeImport>();

            List<TaxEventModel> taxEvents = new List<TaxEventModel>();

            int id = 1;
            foreach (var item in sorted)
            {

                if (item.TransactionType == TransactionType.Buy)
                {
                    holder.Add(item);
                }
                else
                {
                    decimal remaining = item.Quantity;

                    foreach (var item2 in holder.Where(x => x.InstrumentId == item.InstrumentId).ToArray())
                        //Iterate through a copy so we dont get an error about changing array mid loop (ToArray)
                    {
                        if (remaining > 0)
                        {
                            if(item2.Quantity > remaining)
                            {
								taxEvents.Add(new TaxEventModel()
								{
									TaxEventID = id,
									Quantity = remaining,
									StartValue = item2.Value,
                                    EndValue = item.Value,
                                    Instrument = item.Instrument,
									StartDate = item2.TransactionDate,
									EndDate = item.TransactionDate,
									TaxableValue = 0,
                                    Fee = item.TransactionFee + item2.TransactionFee * remaining / item2.Quantity

								});
                                item2.Quantity -= remaining;
                                remaining = 0;
                            }
                            else
                            {
								taxEvents.Add(new TaxEventModel()
								{
									TaxEventID = id,
									Quantity = item2.Quantity,
									StartValue = item2.Value,
                                    EndValue = item.Value,
                                    Instrument = item.Instrument,
									StartDate = item2.TransactionDate,
									EndDate = item.TransactionDate,
									TaxableValue = 0,
                                    Fee = item.TransactionFee + item2.TransactionFee * item2.Quantity / remaining
								});
                                remaining -= item2.Quantity;
                                holder.Remove(item2);
                            }

                            id++;
                        }
                        else
                        {
                            break;
                        }
                    }
                    
                }
            }

            return taxEvents;
        }
    }
}

Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Trader</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/crypto.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/crypto.css" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Dashboard" class="navbar-left"><img style="max-height:50px; padding-right:20px" src="~/images/CryptoTRader.jpg" /></a>
            
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
					



				    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Trades
                        <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu multi-level">
                                <li class="dropdown-submenu">
                                    <a class="test" tabindex="-1" href="#">Trades</a>
                                    <ul class="dropdown-menu">
                                            <li><a class="dropdown_item" tabindex="-1" asp-area="" asp-controller="TradeImport" asp-action="Index">Manage Trades<span class="glyphicon glyphicon-bitcoin menu_logo"></span></a></li>
                                            <li><a class="dropdown_item" asp-area="" asp-controller="TradeAnalysis" asp-action="Index">Analyse trades<span class="glyphicon glyphicon-stats menu_logo"></span></a></li>
                                    </ul>
                                </li>
                                
								<li class="dropdown-submenu">
                                    <a class="test" tabindex="-1" href="#">Imports</a>
                                    <ul class="dropdown-menu">
                                            <li><a class="dropdown_item" asp-area="" asp-controller="FileImport" asp-action="Index">All imports<span class="glyphicon glyphicon-list menu_logo"></span></a></li>
                                            <li><a class="dropdown_item" asp-area="" asp-controller="TradeImport" asp-action="Import">Import trades<span class="glyphicon glyphicon-open menu_logo"></span></a></li>
                                    </ul>
                                </li>

                                <li class="dropdown-submenu">
                                    <a class="test" tabindex="-1" href="#">
                                        Taxes
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a class="dropdown_item" tabindex="-1" asp-area="" asp-controller="Tax" asp-action="Index">Generate Taxes<span class="glyphicon glyphicon-calendar menu_logo"></span></a></li>
                                        <li><a class="dropdown_item" asp-area="" asp-controller="Tax" asp-action="Index">Tax Advice (coming soon)<span class="glyphicon glyphicon-info-sign menu_logo"></span></a></li>
                                    </ul>
                                </li>
                               
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Instruments
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu multi-level">
                            <li class="dropdown-submenu">
                                <a class="test" tabindex="-1" href="#">
                                    News
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a tabindex="-1" asp-area="" asp-controller="NewsItems" asp-action="Index">News board (coming soon)<span class="glyphicon glyphicon-warning-sign menu_logo"></span></a></li>
                                    <li><a asp-area="" asp-controller="NewsItems" asp-action="Index">Events calendar (coming soon)<span class="glyphicon glyphicon-calendar menu_logo"></span></a></li>
                                </ul>
                            </li>

                            <li class="dropdown-submenu">
                                <a class="test" tabindex="-1" href="#">Statistics</a>
                                <ul class="dropdown-menu">
                                    <li><a asp-area="" asp-controller="Instrument" asp-action="Graph">Price graphs<span class="glyphicon glyphicon-usd menu_logo"></span></a></li>
                                    <li><a asp-area="" asp-controller="Instrument" asp-action="Graph">Alerts and stats<span class="glyphicon glyphicon-flash menu_logo"></span></a></li>
                                </ul>
                            </li>
                        </ul>
                    </li>
					<li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Help
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="" asp-controller="Enquiries" asp-action="Index">Enquiries<span class="glyphicon glyphicon-comment menu_logo"></span></a></li>
                            <li><a asp-area="" asp-controller="Home" asp-action="faq">Frequently asked questions<span class="   glyphicon glyphicon-question-sign menu_logo"></span></a></li>
                        </ul>
                    </li>
                    @if (User.IsInRole("Admin"))
                    {
					<li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Admin
                        <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                          <li><a class="dropdown_item" asp-area="" asp-controller="Users" asp-action="Index">Users<span class="glyphicon glyphicon-user menu_logo"></span></a></li>
                          <li><a class="dropdown_item" asp-area="" asp-controller="Exchange" asp-action="Index">Exchanges<span class="glyphicon glyphicon-credit-card menu_logo"></span></a></li>
								<li class="dropdown-submenu">
                                <a class="test" tabindex="-1" href="#">
                                    Instruments
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a asp-area="" asp-controller="Instrument" asp-action="Index">Instruments<span class="glyphicon glyphicon-tags menu_logo"></span></a></li>
                                    <li><a asp-area="" asp-controller="InstrumentPrices" asp-action="Index">Instrument prices<span class="glyphicon glyphicon-gbp menu_logo"></span></a></li>
                                </ul>
                            </li>
                            <li><a class="dropdown_item" asp-area="" asp-controller="Enquiries" asp-action="AdminIndex">Enquiries<span class="glyphicon glyphicon-comment menu_logo"></span></a></li>
                            <li><a class="dropdown_item" asp-area="" asp-controller="NewsItems" asp-action="Index">Manage news<span class="glyphicon glyphicon-globe menu_logo"></span></a></li>
                            <li><a class="dropdown_item" asp-area="" asp-controller="Settings" asp-action="Index">System config<span class="glyphicon glyphicon-cog menu_logo"></span></a></li>
                        </ul>
                    </li>
                    }
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    @await Component.InvokeAsync("InstrumentCarousel")
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Trader</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
			
    </environment>

    @RenderSection("Scripts", required: false)
		<script>
$(document).ready(function(){
  $('.dropdown-submenu a.test').on("click", function(e){
      $(this).next('ul').toggle();
    e.stopPropagation();
    e.preventDefault();
  });
});
</script>
</body>
</html>