Controllers/UserRolesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Trader.Models.AccountViewModels;
using TraderData.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using System.Threading.Tasks;

namespace Trader.Controllers
{
    public class UserRolesController : BaseController
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        public UserRolesController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }

        public ActionResult Index()
        {
            return View();
        }

        // GET: UserRoles/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: UserRoles/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UserRoles/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind("Name")] UserRoleViewModel role)
        {
            if (ModelState.IsValid)
            {
                var exists = await _roleManager.RoleExistsAsync(role.Name);
                if (!exists)
                {
                    var res = await _roleManager.CreateAsync(new IdentityRole { Name = role.Name });
                    return RedirectToAction("Index", "Users");
                }
            }
            return View(role);
        }

        // GET: UserRoles/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: UserRoles/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: UserRoles/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: UserRoles/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/UsersController.cs
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TraderData.Models;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Trader.Models.AccountViewModels;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Trader.Controllers
{
    [Authorize(Roles = "Admin")]//RolesData.SeedRoles(app.ApplicationServices).Wait();
    public class UsersController : BaseController
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public UsersController(UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public IActionResult Index()
        {
            var users = _userManager.Users.ToList();
            return View(users);
        }

        public async Task<IActionResult> Edit(string Id)
        {
            if (Id == null)
            {
                return NotFound();
            }

            var user = await _userManager.FindByIdAsync(Id);
            if (user == null)
            {
                return NotFound();
            }

            var roles = await _roleManager.Roles.ToListAsync();
            var model = new EditUserViewModel
            {
                RoleList = new Microsoft.AspNetCore.Mvc.Rendering.SelectList(roles.Select(x => x.Name)),
                UserID = Id
            };
            return View(model);
        }
        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string UserID, string selRole)
        {
            var user = await _userManager.FindByIdAsync(UserID);
            if (ModelState.IsValid)
            {
                try
                {
                    
                    var res = await _userManager.AddToRoleAsync(user, selRole);
                }
                catch (DbUpdateConcurrencyException)
                {
                    return NotFound();
                }
                return RedirectToAction("Index", "Users");
            }
            return View(user);
        }

        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _userManager.FindByIdAsync(id);
            var roles = await _userManager.GetRolesAsync(user);
            var model = new UserDetailsViewModel
            {
                user = user,
                roles = roles.ToList()
            };
            if (user == null)
            {
                return NotFound();
            }

            return View(model);
        }
    }
}

Views/Users/Details.cshtml
@model Trader.Models.AccountViewModels.UserDetailsViewModel

<div>
    <h4>ApplicationUser</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.user.Id)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.user.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.user.UserName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.user.UserName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.user.NormalizedUserName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.user.NormalizedUserName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.user.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.user.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.user.NormalizedEmail)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.user.NormalizedEmail)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.user.EmailConfirmed)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.user.EmailConfirmed)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.user.SecurityStamp)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.user.SecurityStamp)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.user.ConcurrencyStamp)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.user.ConcurrencyStamp)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.user.PhoneNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.user.PhoneNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.user.PhoneNumberConfirmed)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.user.PhoneNumberConfirmed)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.user.TwoFactorEnabled)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.user.TwoFactorEnabled)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.user.LockoutEnd)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.user.LockoutEnd)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.user.LockoutEnabled)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.user.LockoutEnabled)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.user.AccessFailedCount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.user.AccessFailedCount)
        </dd>
    </dl>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.roles)
            </th>
            <th>
                Actions
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.roles)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item)
                </td>
                <td>
                    <a asp-action="Delete" asp-route-id="@item">Remove</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.user.Id  }) |
    <a asp-action="Index">Back to List</a>
</div>

Views/Users/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Trader.Models.AccountViewModels.EditUserViewModel

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Edit user</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="UserID" />
        <div class="form-group">
            <label asp-for="selRole" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="selRole" asp-items="@Model.RoleList"></select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Users/Index.cshtml
@model IEnumerable<TraderData.Models.ApplicationUser>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<p>
    <a asp-controller="UserRoles" asp-action="Create">Add user role</a>
</p>
<table class="table">
    <thead>
        <tr>
			    <th>
                    @Html.DisplayNameFor(model => model.Id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Email)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UserName)
                </th>
                <th>
                    Actions
                </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
			<td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>