Models/TradeImportModels/TradeImportViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Trader.Models.TradeImportModels
{
    public class TradeImportViewModel
    {
		[Required]
		[Display(Name = "External Reference")]
		public string ExternalReference { get; set; }

		[Required]
		public SelectList InstrumentList { get; set; }

		[Required]
		public int InstrumentId { get; set; }

		[Required]
		public decimal Value { get; set; }

		[Required]
		public decimal Quantity { get; set; }

		[Required]
		[Display(Name = "Transaction date")]
		public DateTime TransactionDate { get; set; }

        public TradeImportViewModel()
        {
        }
    }
}

Controllers/FileImportController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TraderData;
using TraderData.Models.FileImportModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;
using TraderData.Models;

namespace Trader.Controllers
{
    [Authorize]
    public class FileImportController : BaseController
    {
        private readonly IFileImport _fileImport;
        private readonly IReference _reference;
        private readonly UserManager<ApplicationUser> _userManager;

        public FileImportController(IFileImport fileImport, UserManager<ApplicationUser> userManager, IReference reference)
        {
            _fileImport = fileImport;
            _userManager = userManager;
            _reference = reference;
        }

        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        // GET: FileImport
        public async Task<IActionResult> Index()
        {
            var user = await GetCurrentUserAsync();

            var userId = user?.Id;

            if (userId != null)
            {                
                return View(await _fileImport.getAllByUser(userId));
            }
            return NotFound();
            
        }

        // GET: FileImport/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fileImport = await _fileImport.getByIdAsync((int)id);

            if (fileImport == null)
            {
                return NotFound();
            }

            return View(fileImport);
        }

        // GET: FileImport/Create
        public async Task<IActionResult> CreateAsync()
        {
            ViewData["ExchangeId"] = new SelectList(await _reference.getExchanges(), "ExchangeId", "Name");
            return View();
        }

        // POST: FileImport/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FileImportId,Filename,ImportDate,ExchangeId")] FileImport fileImport)
        {
            if (ModelState.IsValid)
            {
                await _fileImport.Add(fileImport);
                
                return RedirectToAction("Index");
            }
            ViewData["ExchangeId"] = new SelectList(await _reference.getExchanges(), "ExchangeId", "Name", fileImport.ExchangeId);
            return View(fileImport);
        }

        // GET: FileImport/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fileImport = await _fileImport.getByIdAsync((int)id);
            if (fileImport == null)
            {
                return NotFound();
            }
            ViewData["ExchangeId"] = new SelectList(await _reference.getExchanges(), "ExchangeId", "Name", fileImport.ExchangeId);
            return View(fileImport);
        }

        // POST: FileImport/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FileImportId,Filename,ImportDate,ExchangeId")] FileImport fileImport)
        {
            if (id != fileImport.FileImportId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var res = await _fileImport.Edit(fileImport);
                if (res)
                    return RedirectToAction("Index");
                else
                    return NotFound();
            }
            ViewData["ExchangeId"] = new SelectList(await _reference.getExchanges(), "ExchangeId", "Name", fileImport.ExchangeId);
            return View(fileImport);
        }

        // GET: FileImport/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fileImport = await _fileImport.getByIdAsync((int)id);
            if (fileImport == null)
            {
                return NotFound();
            }

            return View(fileImport);
        }

        // POST: FileImport/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _fileImport.Delete(id);
            return RedirectToAction("Index");
        }

        
    }
}

Controllers/TradeImportController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TraderData;
using Trader.Models.FileImportModels;
using Trader.Models.TradeImportModels;
using TraderData.Models;
using TraderData.Models.TradeImportModels;
using TraderData.Models.FileImportModels;

namespace Trader.Controllers
{
    [Authorize]
    public class TradeImportController : BaseController
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ITrades _trades;
        private readonly IReference _reference;

		public TradeImportController(ITrades trades, IReference reference, UserManager<ApplicationUser> userManager)
		{
			_trades = trades;
            _userManager = userManager;
            _reference = reference;
        }


		// GET: TradeImport
		public async Task<IActionResult> Index(
			string sortOrder,
			string currentFilter,
			string searchString,
			int? page)
        {

            var user = await GetCurrentUserAsync();

			var userId = user?.Id;

            if (userId != null)
            {
				ViewData["CurrentSort"] = sortOrder;
				ViewData["DateSortParm"] = sortOrder == "Date" ? "Date_desc" : "Date";
				ViewData["ValueSortParm"] = sortOrder == "Price" ? "Price_desc" : "Price";
				ViewData["QuantitySortParm"] = sortOrder == "Qty" ? "Qty_desc" : "Qty";

				if (searchString != null)
				{
					page = 1;
				}
				else
				{
					searchString = currentFilter;
				}

				ViewData["CurrentFilter"] = searchString;


                var tradesAll = await _trades.getAllByUser(userId);

				var trades = tradesAll.Select(x => x);

				if (!String.IsNullOrEmpty(searchString))
				{
					if (IsNumber(searchString))
					{
						trades = trades.Where(s => s.Value > int.Parse(searchString));
					}
					else
					{
						trades = trades.Where(s => s.Instrument.Name.Contains(searchString)
                                             || s.TransactionDate.ToString().Contains(searchString)
                                             || s.FileImport.Exchange.Name.Contains(searchString));
					}
				}
				switch (sortOrder)
				{
					case "Price":
						trades = trades.OrderBy(s => s.Value);
						break;
					case "Price_desc":
						trades = trades.OrderByDescending(s => s.Value);
						break;
					case "Date":
						trades = trades.OrderBy(s => s.TransactionDate);
						break;
					case "Date_desc":
						trades = trades.OrderByDescending(s => s.TransactionDate);
						break;
					case "Qty":
						trades = trades.OrderBy(s => s.Quantity);
						break;
					case "Qty_desc":
						trades = trades.OrderByDescending(s => s.Quantity);
						break;
					default:
						trades = trades.OrderBy(x => x.TransactionDate).ToList();
						break;
				}
				int pageSize = 50;
				return View(PaginatedList<TradeImport>.Create(trades.AsQueryable(), page ?? 1, pageSize));
            }
            return NotFound();
        }
		internal bool IsNumber(string s)
		{
			int i;
			return int.TryParse(s, out i);
		}
        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        // GET: TradeImport/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tradeImport = await _trades.getById((int)id);
            if (tradeImport == null)
            {
                return NotFound();
            }

            return View(tradeImport);
        }

        // GET: TradeImport/Create
        public async Task<IActionResult> Create()
        {
            IEnumerable<Instrument> instrument = await _reference.getInstruments();
            var instruments = instrument.OrderBy(c => c.Name).Select(x => new { Id = x.InstrumentID, Value = x.Name });
			var model = new TradeImportViewModel();
			model.InstrumentList = new SelectList(instruments, "Id", "Value");

			return View(model);
        }

        // POST: TradeImport/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(string ExternalReference, int InstrumentId, decimal Value, decimal Quantity,DateTime TransactionDate)
        {
            if (ModelState.IsValid)
            {
                TradeImport trade = new TradeImport()
                {
                    ExternalReference = ExternalReference,
                    InstrumentId = InstrumentId,
                    Value = Value,
                    Quantity = Quantity,
                    TransactionDate = TransactionDate
                };

                return RedirectToAction("Index");
            }
            IEnumerable<Instrument> instrument = await _reference.getInstruments();
            var instruments = instrument.OrderBy(c => c.Name).Select(x => new { Id = x.InstrumentID, Value = x.Name });
			var model = new TradeImportViewModel(); //tradeImport;
            model.ExternalReference = ExternalReference;
            model.Quantity = Quantity;
            model.Value = Value;
            model.TransactionDate = TransactionDate;
			model.InstrumentList = new SelectList(instruments, "Id", "Value", InstrumentId);
            return View(model);
        }

        // GET: TradeImport/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tradeImport = await _trades.getById((int)id);
            if (tradeImport == null)
            {
                return NotFound();
            }
            return View(tradeImport);
        }

        // POST: TradeImport/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TradeImportID,ExternalReference,InstrumentId,Value,Quantity,TransactionDate,UserID,FileImportId")] TradeImport tradeImport)
        {
            if (id != tradeImport.TradeImportID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
				try
				{
					var res = await _trades.Edit(tradeImport);
				}
				catch (DbUpdateConcurrencyException)
				{
                    var exists = await _trades.TradeImportExists(tradeImport.TradeImportID);

                    if (!exists)
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
                return RedirectToAction("Index");
            }
            return View(tradeImport);
        }

        // GET: TradeImport/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tradeImport = await _trades.getById((int)id);
            if (tradeImport == null)
            {
                return NotFound();
            }

            return View(tradeImport);
        }

        // POST: TradeImport/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            _trades.Delete(id);
            return RedirectToAction("Index");
        }



        public async Task<IActionResult> Import()
        {
            IEnumerable<Instrument> instrument = await _reference.getInstruments();
            IEnumerable<Exchange> exchange = await _reference.getExchanges();
			var instruments = instrument.OrderBy(c => c.Name).Select(x => new { Id = x.InstrumentID, Value = x.Name });
            var exchanges = exchange.OrderBy(c => c.Name).Select(x => new { Id = x.ExchangeId, Value = x.Name });
            var model = new ImportModel();
            model.ExchangeList = new SelectList(exchanges, "Id", "Value");
			model.InstrumentList = new SelectList(instruments, "Id", "Value");
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Import(IFormFile file, int selInstrument, int selExchange)
        {
            var user = await GetCurrentUserAsync();

            var userId = user?.Id;

            if (userId != null)
            {
                int count = 0;
                FileImport fileImport;
                using (var reader = new StreamReader(file.OpenReadStream()))
                {
                    //var fileContent = reader.ReadToEnd();
                    var parsedContentDisposition = ContentDispositionHeaderValue.Parse(file.ContentDisposition);
                    fileImport = new FileImport
                    {
                        Filename = parsedContentDisposition.FileName,
                        ExchangeId = selExchange,
                        ImportDate = DateTime.Now,
                        UserID = userId

                    };
                    List<TradeImport> trades = new List<TradeImport>();
                    while (!reader.EndOfStream)
                    {
                        var line = reader.ReadLine();
                        count += 1;
                        if (count >= 5)
                        {
                            var data = line.Split(new[] { ',' });
                            var trade = new TradeImport()
                            {
                                ExternalReference = data[9],

Views/TradeImport/Edit.cshtml
@model TraderData.Models.TradeImportModels.TradeImport

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>TradeImport</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="TradeImportID" />
		<input type="hidden" asp-for="UserID" />
		<input type="hidden" asp-for="InstrumentId" />
		<input type="hidden" asp-for="FileImportId" />
        <div class="form-group">
            <label asp-for="ExternalReference" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ExternalReference" class="form-control" />
                <span asp-validation-for="ExternalReference" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Value" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Value" class="form-control" />
                <span asp-validation-for="Value" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Quantity" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="TransactionDate" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="TransactionDate" class="form-control" />
                <span asp-validation-for="TransactionDate" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ImportDate" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ImportDate" class="form-control" />
                <span asp-validation-for="ImportDate" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/TradeImport/Index.cshtml
@model PaginatedList<TraderData.Models.TradeImportModels.TradeImport>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<p>
    <a asp-action="Import">Import</a>
</p>
<p>
    <a href="/Tax/Index">Get Taxes</a>
</p>
<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Find by name: <input type="text" name="SearchString" value="@ViewData["currentFilter"]" />
            <input type="submit" value="Search" class="btn btn-default" /> |
            <a asp-action="Index">Back to Full List</a>
        </p>
    </div>
</form>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model[0].ExternalReference)
                </th>
			    <th>
                    @Html.DisplayNameFor(model => model[0].TransactionType)
                </th>
			    <th>
                    @Html.DisplayNameFor(model => model[0].Instrument.Name)
                </th>
                <th>
                    <a asp-action="Index" asp-route-sortOrder="@ViewData["ValueSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Value</a>
                </th>
                <th>
                    <a asp-action="Index" asp-route-sortOrder="@ViewData["QuantitySortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Quantity</a>
                </th>
                <th>
                    <a asp-action="Index" asp-route-sortOrder="@ViewData["DateSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Date time</a>
                </th>
			    <th>
                    @Html.DisplayNameFor(model => model[0].TransactionFee)
                </th>
			    <th>
				    @Html.DisplayNameFor(model => model[0].FileImport)
			    </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ExternalReference)
            </td>
			<td>
                @Html.DisplayFor(modelItem => item.TransactionType)
            </td>
			<td>
                @Html.DisplayFor(modelItem => item.Instrument.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Value)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
			
            <td>
                @Html.DisplayFor(modelItem => item.TransactionDate)
            </td>
			<td>
                @Html.DisplayFor(modelItem => item.TransactionFee) @Html.DisplayFor(modelItem => item.Currency)
            </td>
			<td>
                <a asp-controller="FileImport" asp-action="Details" asp-route-id="@item.FileImportId">Import</a>
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.TradeImportID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.TradeImportID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.TradeImportID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-page="@(Model.PageIndex - 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @prevDisabled">
    Previous
</a>
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-page="@(Model.PageIndex + 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @nextDisabled">
    Next
</a>